baseURL = 'https://www.pusu.life/'
languageCode = 'zh-cn'
title = '蒲素的博客'

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 10
  [[menu.main]]
    name = '归档'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 30

[params]
  author = '蒲素'
  description = '技术博客与思考'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
